tc-build: Ditch os / os.path for pathlib wherever possible
We want to avoid converting between PosixPath and str implicity because
prior to Python 3.6, many of the os methods wouldn't accept it,
resulting in a nice stacktrace (this one is from Debian's Python 3.5.3):

Traceback (most recent call last):
  File "./build-llvm.py", line 252, in <module>
    main()
  File "./build-llvm.py", line 245, in main
    fetch_llvm_binutils(root, not args.no_pull, args.branch)
  File "./build-llvm.py", line 156, in fetch_llvm_binutils
    subprocess.run(["git", "clone", "-b", branch,
"git://github.com/llvm/llvm-project", p], check=True)
  File "/usr/lib/python3.5/subprocess.py", line 383, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1221, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: Can't convert 'PosixPath' object to str implicitly

Pathlib has most of what we need and we can use the as_posix method to
get a stirng version of the path whenever we have to have it.

Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>