build-llvm.py: Switch to dict() over dictionary comprehension
Something is going wrong with the comprehension, as there is a
ValueError when unpacking the define (which makes little sense):

  Traceback (most recent call last):
    File ".../tc-build/./build-llvm.py", line 521, in <module>
      defines = {k: v for define in args.defines for1 k, v in define.split('=', 1)}
    File ".../tc-build/./build-llvm.py", line 521, in <dictcomp>
      defines = {k: v for define in args.defines for k, v in define.split('=', 1)}
  ValueError: too many values to unpack (expected 2)

This can be worked around by just using the dict() constructor, which is
simpler to read anyways.

Signed-off-by: Nathan Chancellor <nathan@kernel.org>