build-llvm.py: Fix 'LLVM source location does not exist' error message
The wrong folder is being used, which results in:

  Traceback (most recent call last):
    File ".../build-llvm.py", line 1620, in <module>
      main()
    File ".../build-llvm.py", line 1607, in main
      linux_folder.as_posix())
  AttributeError: 'NoneType' object has no attribute 'as_posix'

Signed-off-by: Nathan Chancellor <nathan@kernel.org>